name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: npm install
        run: npm install
        env:
          CI: true
      - name: npm run pretest
        run: npm run pretest
        env:
          CI: true
